### ISSUE TITLE
Nominet parsing

### ISSUE THREAD

**Issue by meamens** [joepie91/python-whois#8]
Hi,

When running against .co.uk domains this seems to be excluding contact information. (when searching 'google.co.uk' address information is included in raw output but not parsed by the code). I've also noticed it seems to be missing the "Registration status:" field too.

Thanks

**Comment by joepie91** [comment]
The issue has been fixed - both the registrant and registration status parsing - and a new version with the fix has been released. You can run `pip install --upgrade pythonwhois` to update pythonwhois on your system to the fixed version.

**Comment by meamens** [comment]
Hi Sven,

Thank you very much for taking time to do this. I've just tried though and
maybe I'm done something wrong, but it still doesn't appear to retrieve all
expected information (i.e. in comparison to output from .com domains). As
an example, the domain 'baligems.co.uk' has address information when
looking at raw output, but this information isn't present when run
normally. Would it be possible to include this in the output?

Thanks,
Marc

**Comment by joepie91** [comment]
Seems like Nominet is a bit of a problem child :)

I'll have a look at baligems.co.uk in a moment.

**Comment by joepie91** [comment]
The problem turned out to be the "Trading as" field. I've changed the regex to allow arbitrary other data inbetween the registrant name and address, and it should work correctly now for baligems.co.uk.

Please let me know if there are any other domains that are not working correctly; if there are multiple problematic domains, it'd be preferable if you could post a complete list here so I can look at all of them.

I'll wait until tomorrow to push the updated version; that way, if you have any other broken domains, I can get the fixes for that into the same update :)

**Comment by meamens** [comment]
Hi Sven,

Thanks ever so much for this. I am sorry for the delay with responding, it
was rather a busy week and weekend! So how can I test the new version? I've
downloaded the latest I can find (v2.1.2) and it still appears to have the
same issue, i.e. no registrant info for baligems.co.uk.

I should be free to troubleshoot most evenings this week, so will be
getting back to you much sooner from now on

Thanks again,
Marc.

**Comment by joepie91** [comment]
I haven't shipped the fixed version yet - I've been quite busy as well, so I figured I'd just wait a bit longer for feedback before packaging and uploading it. If you'd like to test the (unreleased) new version yourself, you could clone the repository and switch to the develop branch (`git clone https://github.com/joepie91/python-whois.git` & `git checkout develop`), but depending on your operating system, Git might be a bit unwieldy to setup if you don't have it yet. If you do decide to take this route, you can just run `./pwhois` instead of `pwhois`, and it'll use the version from the repository.

Alternatively, if you provide me with a list of domains that are causing problems in the current (2.1.2) version, I can run through all of them, add test cases, and fix them where necessary. Just let me know which option you prefer.

**Comment by meamens** [comment]
Well that certainly explains why I couldn't find it! :) I've just done some
quick testing and it looks much better for the 10 or so .co.uk domains I
tried. Unfortunately I've now found a problem with a
globaltravelgroup.comnot showing registrant info.

I will do a full run and get back to you with anything else I see amiss.

Thanks

**Comment by joepie91** [comment]
Alright, globaltravelgroup.com is fixed - turned out that the regular expression for that format only supported up to 2 address lines, and this one has 3. I've upped it to 3 address lines.

Awaiting a further list :)

**Comment by joepie91** [comment]
I have shipped version 2.1.3, which contains fixes for the domains you've provided so far. You can upgrade using `pip install --upgrade pythonwhois`.

Please reopen this issue or create a new issue if/when you have a list of other problematic domains.

**Comment by meamens** [comment]
Hi Sven,

I did some work on this last night, I'm still compiling results so haven't
got a definitive list of domains as yet but here are my findings so far:-

.eu domains don't give all information (I think a visit to www.eurid.eu is
necessary to obtain this, but I only have 6 of these so I can do that
manually)
globallatedeals.com doesn't parse contact details, this whois is provided
by LCN
Including the domain name in the results would be perfect, you could even
expand on this to provide output when a name is not found, e.g.:-
 Domain: NAME
 Status : Not Registered

I'll let you know of any other problem domains but I think you've covered
most of what I need so far, thank you.

**Comment by joepie91** [comment]
I've updated the code to support LCN.com WHOIS data, it is now parsed correctly.

As for the EURid contact details, the details given by their WHOIS server are very limited, and that would indeed require a web-based lookup. This is planned to be implemented in the future, but it's unclear when - especially CAPTCHAs have the potential to cause trouble. A ticket for this exists at #13.

As for the indication of a domain not being registered, I've created a ticket for this at #14. I'd recommend subscribing to both of these tickets if you'd like to be notified of updates to them.

As for including the domain name in the output; I've looked into this, but it's non-trivial, due to the way the pythonwhois code is structured. I might look into this in the future, but a far easier solution (at least for now), would be to simply 'remember' the domain that is looked up in the code that is using pythonwhois. The output of pythonwhois would never have a different domain from the input anyway; it's always an exact match, so there's not much added value in having it returned by the library.

**Comment by meamens** [comment]
Fantastic, thanks Sven it's now almost perfect for my needs. Don't worry
about domain name output, I think I can get this using bash.

One thing I've noticed which I suspect may be a bug, is some 'not found'
domains are still giving output for "Last updated", i.e. './pwhois
nonexistingdomain.com' gives "Last update       : 2014-04-29 12:23:48"
parsed from the line >>> Last update of whois database: Tue, 29 Apr 2014
12:23:48 UTC <<<

I can work around this though so if it is meant to be there, don't worry.

Thanks!

**Comment by joepie91** [comment]
Yeah, that's more-or-less supposed to happen. pythonwhois is meant to just output whatever data it can find, even if it can't determine whether a domain exists or not - and since some servers always return "last database update" timestamps, that field may be filled even if the domain doesn't exist.

It's not really possible to prevent that from happening until #14 is implemented, as different WHOIS servers have wildly different definitions of "last update" - some use it to refer to the last time the WHOIS data for a domain was updated, some use it for the last time it was renewed, and yet others use it for the last time they ran a script to import new WHOIS data into the database as a whole.
